version: 2.0
jobs:
  build:
    docker:
      - image: membrane/bionic-membrane:latest
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout
      - run: add-apt-repository -y ppa:jonathonf/ffmpeg-4
      - run: apt-get update -qq
      - run: apt-get install -q -y libavcodec-dev libavformat-dev libavutil-dev
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
